server:
  port: 8082
#  servlet:
#    context-path: /ems-thymeleaf

#spring:
#  thymeleaf:
#    cache: false
#    prefix: classpath:/templates/
#    suffix: .html
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ems-thymeleaf?characterEncoding=UTF-8&&useSSL=false&&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#  web:
#    resources:
#      static-locations: classpath:/static/,file:${photo.file.dir} #暴露哪些资源可以通过项目名访问
#
#
#mybatis:
#  mapper-locations: classpath:com/cn/mapper/*.xml
#  type-aliases-package: com.cn.entity
#
#
##控制台日志输出
#logging:
#  level:
#    root: info
#    com.cn: debug
#
##指定文件上传位置
#photo:
#  file:
#    dir: D:\21 物联 陈诺\work\cn\photos